<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Booking Wizard</title>

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./css/style.css?t=<?= filemtime("./css/style.css"); ?>">
    <script src='../wireframe.js'></script>
</head>

<body>

<div id="background"></div>
<!-- Header & Navbar container -->
<div class="header-nav-container" id="header-nav-container">
    <!-- Header -->
    <?php include "components".DIRECTORY_SEPARATOR."header.php"?>
    <!-- Navbar -->
    <?php include "components".DIRECTORY_SEPARATOR."navbar.php"?>

</div>

<main>
    <article id='Website Under Construction'>
        <!-- Creative Commons image sourced from https://pixabay.com/en/maintenance-under-construction-2422173/ and used for educational purposes only -->
        <img src='../../media/website-under-construction.png' alt='Website Under Construction' />
    </article>
</main>


<?php include "components".DIRECTORY_SEPARATOR."footer.php"; ?>
<?php include "components".DIRECTORY_SEPARATOR."debugbar.php";?>


</body>
</html>


<!-- Sticky Navbar script by W3 schools https://www.w3schools.com/howto/howto_js_navbar_sticky.asp -->
<script src="javascript/navbar.js"></script>