<?php
//include PHP Classes
use components\Movie;
use components\Seat;

include "components". DIRECTORY_SEPARATOR . "Movie.php";
include "components". DIRECTORY_SEPARATOR . "Seat.php";

//load movies and seats from Json file
$moviesJson = file_get_contents("movies.json");
$movies = [];

//load seating from json
$seatsJson = file_get_contents("seating.json");
$seating = [];

//perform the foreach loop to decode the json and create the seat objects and place them in the seating array
foreach(json_decode($seatsJson) as $seat){
    $seating[] = new Seat((array)$seat);
}

//perform a foreach loop to decode the json into a php array and create a movie object based of it
foreach (json_decode($moviesJson) as $movie){
    $movies[] = new Movie((array)$movie);
}

//check if we have passed a $_GET code, if not return them to the index page with an error, else check for a valid code
if(!isset($_GET['code'])){
    header("Location: ./index.php?error=invalid_film#now-showing");
}else{
    //create our result variable
    $result = false;
    $film = null;
    //check if any film matches that code
    foreach ($movies as $movie){
        if($movie->getCode() == $_GET['code']){
            $result = true;
            $film = $movie;
        }
    }
    //finally check for a invalid result, if so return to the index page with the invalid film error
    if(!$result){
        header("Location: ./index.php?error=invalid_film#now-showing");
    }
}



?>

<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Booking Wizard</title>

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./css/style.css?t=<?= filemtime("./css/style.css"); ?>">
    <script src='../wireframe.js'></script>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Poppins:ital,wght@0,400;1,700&display=swap" rel="stylesheet">
</head>

<body>

<div id="background"></div>
<!-- Header & Navbar container -->
<div class="header-nav-container" id="header-nav-container">
    <!-- Header -->
    <?php include "components".DIRECTORY_SEPARATOR."header.php"?>
    <!-- Navbar -->
    <?php include "components".DIRECTORY_SEPARATOR."navbar.php"?>

</div>

<main id="booking-container">
    <section>
        <h2>Booking Wizard: <?php echo $film->getTitle()?></h2>
        <iframe width="560" height="315" src="<?php echo $film->getTrailer()?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </section>
    <section>
        <form action="./booking.php?code=<?php echo $film->getCode()?>" method="post">
            <div>
            <h3>Movie Details</h3>
            <label for="movie">Movie:</label><br>
            <input type="text" id="movie" name="movie" value="<?php echo $film->getTitle()?>" readonly><br>
            <input type="text" id="movie_code" name="movie_code" value="<?php echo $film->getCode()?>" hidden><br>
            </div>
            <div>
            <h3>Your Details</h3>
            <label for="full_name">Fullname:</label><br>
            <input type="text" id="full_name" name="full_name" required placeholder="john smith"><br>
            <label for="email">Email:</label><br>
            <input type="text" id="email" name="email" required placeholder="me@example.com"><br>
            <label for="mobile_number">Mobile Number:</label><br>
            <input type="text" id="mobile-number" name="mobile_number" required placeholder="0421 123 123"><br>
            </div>
            <div>
            <h3>Date & Time</h3>
            <?php
            $times = $film->getTimes();
            $time_ids = $film->getTime24();

            $i = 0;
            while($i < count($times)){
                echo "<input type='radio' id='".$time_ids[$i]."' name='date' value='".$time_ids[$i]."' class='radio-button'>";
                echo "<lable for='".$time_ids[$i]."'>".$times[$i]."</lable><br>";
                $i++;
            }
            ?>
            </div>
            <div>
            <h3>Seating</h3>
            <?php
            //I have decided to use radio buttons instead of a 1-5 number input as its more user-friendly to the user and can be easily implemented with my json setup
            $i = 0;
            while($i < count($seating)){
                echo "<input type='radio' id='".$seating[$i]->getCode()."' name='seat-code' value='".$seating[$i]->getCode()." '>";
                echo "<lable for='".$seating[$i]->getCode()."'>".$seating[$i]->getName()."</lable><br>";
                $i ++;
            }
            ?>
            </div>
            <div>
            <button type="submit">Create Booking</button>
            </div>


        </form>
    </section>
</main>


<?php include "components".DIRECTORY_SEPARATOR."footer.php"; ?>
<?php include "components".DIRECTORY_SEPARATOR."debugbar.php";?>


</body>
</html>


<!-- Sticky Navbar script by W3 schools https://www.w3schools.com/howto/howto_js_navbar_sticky.asp -->
<script src="javascript/navbar.js"></script>