<?php
//import PHP componment
use components\Movie;
use components\Seat;

//include PHP Classes
include "components". DIRECTORY_SEPARATOR . "Movie.php";
include "components". DIRECTORY_SEPARATOR . "Seat.php";

//load movies and seats from Json file
$moviesJson = file_get_contents("movies.json");
$movies = [];
$seatsJson = file_get_contents("seating.json");
$seating = [];


//perfrom a foreach loop to decode the json into a php array and create a movie object based of it
foreach (json_decode($moviesJson) as $movie){
    $movies[] = new Movie((array)$movie);
}
//perform the foreach loop to decode the json and create the seat objects and place them in the seating array
foreach(json_decode($seatsJson) as $seat){
    $seating[] = new Seat((array)$seat);
}
?>

<!DOCTYPE html>
<html lang='en'>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Cinema</title>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./css/style.css?t=<?= filemtime("./css/style.css"); ?>">

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <script src='../wireframe.js'></script>

    <script src="javascript/seatingSlider.js"></script>



  </head>

  <body>
  <div id="background"></div>
  <div id="background-2"></div>

  <!-- Header & Navbar container -->
    <div class="header-nav-container" id="header-nav-container">
        <!-- Header -->
        <?php include "components".DIRECTORY_SEPARATOR."header.php"?>
        <!-- Navbar -->
        <?php include "components".DIRECTORY_SEPARATOR."navbar.php"?>

    </div>

  <!-- Main Page Content -->
    <main>
        <section id="about-us">
            <h2>About Us</h2>
            <p>add stuff here!</p>
        </section>
        <section id="seats-and-prices">
            <h2>Seats and Prices ....</h2>
            <div class="flex">
                <div class="left">
                    <div class="flex">
                        <div class="left">
                            <h4>Seats</h4>
                            <?php
                            foreach ($seating as $seat){
                                $seat->renderType();
                            }
                            ?>
                        </div>
                        <div class="middle">
                            <h4>Price</h4>
                            <?php
                            foreach ($seating as $seat){
                                $seat->renderPrice();
                            }
                            ?>
                        </div>
                        <div class="middle">
                            <h4>Discounted Price</h4>
                            <?php
                            foreach ($seating as $seat){
                                $seat->renderDiscountedPrice();
                            }
                            ?>
                        </div>

                        <div class="middle">
                            <h4>Discount Times</h4>

                            <?php
                            foreach ($seating as $seat){
                                echo "<p> Times <span data-tooltip='";
                                $seat->renderDiscountTimes();
                                 echo " '><img src='../../media/svg/clock.svg' alt='Clock Icon'></span></p>";
                            }
                            ?>

                        </div>
                    </div>

                </div>
                <div class="right">
                    <div id="imageSlider">
                    <?php
                    foreach ($seating as $seat){
                            if($seat->hasImage()) {
                                echo "<div class='slide'>";
                                $seat->renderType("h3");
                                $seat->renderImage();
                                echo "</div>";

                            }
                    }
                    ?>
                    </div>
                </div>

            </div>

        </section>
        <section id="now-showing">
            <h2>Now Showing ....</h2>
            <div id="movie-cards">
            <?php
            //render each movie in the now showing section
            foreach ($movies as $movie){
                $movie->render();
            }?>
            </div>
        </section>

    </main>

  <?php include "components".DIRECTORY_SEPARATOR."footer.php"?>

  <?php include "components".DIRECTORY_SEPARATOR."debugbar.php";?>

  </body>
</html>


<!-- Sticky Navbar script by W3 schools https://www.w3schools.com/howto/howto_js_navbar_sticky.asp -->
<script src="javascript/navbar.js"></script>
