<?php
//Debugbar message example
use components\Console;

$message[] = "Luncardo Debugbar v0.1, created by Jack harris 30/12/2021";

//include PHP Console log
include "components". DIRECTORY_SEPARATOR . "Console.php";

$test = ["abc" => "string", 123 => "number"];
Console::log($test);
Console::log($_GET);
?>

<!DOCTYPE html>
<html lang='en'>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Cinema</title>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./css/style.css?t=<?= filemtime("./css/style.css"); ?>">

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <script src='../wireframe.js'></script>



  </head>

  <body>
  <div id="background"></div>
  <!-- Header & Navbar container -->
    <div class="header-nav-container" id="header-nav-container">
        <!-- Header -->
        <?php include "components".DIRECTORY_SEPARATOR."header.php"?>
        <!-- Navbar -->
        <?php include "components".DIRECTORY_SEPARATOR."navbar.php"?>

    </div>

  <!-- Main Page Content -->
    <main>
        <section id="about-us">
            <h2>About Us</h2>
            <p>add stuff here!</p>
        </section>
        <section id="seats-and-prices">
            <h2>Seats and Prices</h2>
            <p>add stuff here!</p>
        </section>
        <section id="now-showing">
            <h2>Now Showing</h2>
            <div class="card-container">
                <div class="card" tabindex="1234">
                    <div class="front">Im the front!</div>
                    <div class="back">Hello front, im the back</div>
                </div>
            </div>
        </section>

    </main>

  <?php include "components".DIRECTORY_SEPARATOR."footer.php"?>

  <?php include "components".DIRECTORY_SEPARATOR."debugbar.php";?>

  </body>
</html>


<!-- Sticky Navbar script by W3 schools https://www.w3schools.com/howto/howto_js_navbar_sticky.asp -->
<script src="javascript/navbar.js"></script>
