<!DOCTYPE html>
<html lang='en'>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Cinema</title>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./css/style.css?t=<?= filemtime("./css/style.css"); ?>">

      <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <script src='../wireframe.js'></script>
  </head>

  <body>
  <div id="background"></div>
  <!-- Header & Navbar container -->
    <div class="header-nav-container">
        <!-- Header -->
        <?php include "components".DIRECTORY_SEPARATOR."header.php"?>
        <!-- Navbar -->
        <?php include "components".DIRECTORY_SEPARATOR."navbar.php"?>

    </div>

  <!-- Main Page Content -->

    <main>
        <section id="landing">
            <h2>Landing</h2>
        </section>
        <section>
            <h2>About Us</h2>
            <p>add stuff here!</p>
        </section>
        <section>
            <h2>Seats and Prices</h2>
            <p>add stuff here!</p>
        </section>
        <section>
            <h2>Now Showing</h2>
            <p>add stuff here!</p>
        </section>

    </main>

  <?php include "components".DIRECTORY_SEPARATOR."footer.php"?>


  </body>
</html>
