<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lunardo Cinema</title>
    <!-- 64pixel Favicon logo & logo SVG created by Jack Harris -->
    <link rel="shortcut icon" type="image/png" href="../../media/png/favicon.png">
    <!-- Custom CSS generated by the Sass preprocessor, created by Jack Harris -->
    <link id='stylecss' type="text/css" rel="stylesheet" href="./resources_css/?file=style">
    <?php if($GLOBALS["endpoint"] == "/confirmation"){
        echo '<link id="stylecss" type="text/css" rel="stylesheet" href="./resources_css/?file=confirmation">';
    }?>

    <?php if($GLOBALS["endpoint"] == "/booking"){
        echo '<link id="stylecss" type="text/css" rel="stylesheet" href="./resources_css/?file=a4">';
    }?>

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <script src='../wireframe.js'></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Poppins:ital,wght@0,400;1,700&display=swap" rel="stylesheet">


</head>